@startuml
|kunde|
start
:gå til website;
|#AntiqueWhite|website|
:vælg "quick-byg" og mål på carport;
:udfyld kontakt formular og send forespørgsel;
|martin|
:modtager email med forespørgsel;
|program|
:indtast kundens carport data MANUELT!;
:visuel repræsentation af carport]
:stykliste]
|martin|
:kontakt kunde via tfl;
|kunde|
:betaling;
|program|
|kunde|
:modtager stykliste;
|martin|
:gem ordre i database;
:send kvittering;
|kunde|
:modtager carport;
@enduml
