@startuml
object product{
name
price
unit
}

object partsListLine{
length
price
quantity
description
}

object order{
width
length
price
}

object user{
email
password
name
address
role
balance
}

order "*" o- "1" user
partsListLine "*" -o "1" order
product "*" -o "1" partsListLine

@enduml